---
- name: Update hwdb
  become: true
  ansible.builtin.command: systemd-hwdb update
  changed_when: true

- name: Trigger udev
  become: true
  ansible.builtin.command: udevadm trigger -s input
  changed_when: true

- name: Restart keylightc
  become: true
  ansible.builtin.systemd:
    name: keylightc
    state: restarted
    daemon_reload: true
