---
backup_enabled: false
backup_calendar: "hourly"
backup_repository: /mnt/nas/SystemSnapshots
backup_nas_ip: "192.168.1.10"
backup_battery_threshold: 40
backup_ping_timeout: 1
backup_mount_timeout: 10
backup_nice_level: 19
backup_ionice_class: 3
