---
all:
  hosts:
    laptop:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
    desktop:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
    minio-dev:
      ansible_host: minio-dev.lan
      ansible_user: erik
