---
# Development sites to proxy
# Maps domains to localhost ports
dev_sites:
  - domain: naaccord.test
    port: 8040
  - domain: academic.test
    port: 8010
    wildcard: true
  - domain: erikwestlund.test
    port: 8010
    wildcard: true
  - domain: erik-westlund.data-scientist.page
    port: 8010
  - domain: better-shoes.test
    port: 8020
    wildcard: true
  - domain: framework.test
    port: 5175
  - domain: framework-site.test
    port: 8032
  - domain: flint.test
    port: 8031
  - domain: wordlegroup.test
    port: 8033
  # Local services
  - domain: local.syncthing.lan
    port: 8384

# Shared dev services
dev_sites_extra:
  - domain: mailpit.test
    port: 8025
  - domain: minio.test
    port: 9001
