---
# Development sites to proxy
# Maps domains to localhost ports
dev_sites:
  - domain: naaccord.test
    port: 8000
  - domain: academic.test
    port: 8010
    wildcard: true
  - domain: better-shoes.test
    port: 8020
    wildcard: true
  # Local services
  - domain: local.syncthing.lan
    port: 8384
